### ISSUE TITLE
Search Field not enable 

### ISSUE THREAD

**Issue by arishanapalli** [applidium/ADOverlayContainer#32]
The search field is not enable!
Unable to enter any text inside searchBar.

One more In cocoacontrols its says objective-C but the project build in swift.

**Comment by gaetanzanella** [comment]
Where? In which searchbar?

**Comment by RodBrown1988** [comment]
I think @arishanapalli may be referring to the sample code that's associated with the project has a search field in the UI but it is not selectable/editable. This is because the "DetailHeaderView.xib" file has the checkbox for the search bar's "User Interaction Enabled" state to `false` which will ensure it doesn't receive touches. This confused me a bit when I started working with it.

Enabling this field may require further work to ensure that the overlay container is pushed to its maximum position when the search field begins editing, which is cool, but may fight the goal of simplicity for your sample code.

**Comment by gaetanzanella** [comment]
Thanks @RodBrown1988. You're right. I close this issue because it's an intentional choice.
